### ISSUE TITLE
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by erving666** [hcnoh/knowledge-tracing-collection-pytorch#1]
Hello, bro. Great work!
When I tried to run the code, I got this following:

> python train.py --model_name dkt --dataset_name ASSIST2009

```python
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main(args.model_name, args.dataset_name)
  File "train.py", line 92, in main
    train_dataset, test_dataset = random_split(
  File "/home/yuwei/Studio/env_ervin/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 386, in random_split
    indices = randperm(sum(lengths), generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```

I have torch  "1.10.0+cu113" on 2080Ti and Ubuntu20.
Appreciate your help, bro.

**Comment by erving666** [comment]
Note: There are some bugs in the pytorch.utils.data module on the PyTorch version 1.9.0. If you want to run this repository safely, you need to install the PyTorch version 1.7.0 or 1.8.0.
